[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]
dependencies = ["test"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["format"]

[tasks.cp]
command = "cp"
args = ["target/wasm32-unknown-unknown/release/smart_contract.wasm", "./res/"]
dependencies = ["build"]

[tasks.custom-default]
dependencies = [
    "format",
    "test",
    "build",
    "cp"
]

[tasks.default]
alias = "custom-default"